export const pathAssets = {
	iconQuotes: '../../../../../assets/icons/icon-quotes.svg',
	iconClosed: '../../../../assets/icons/icon-close-sidebar.svg',
	iconOpened: '../../../../assets/icons/icon-hamburger.svg',
	iconArrowUp: '../../../../assets/icons/arrow-up.svg',
	iconArrowLeft: '../../../../assets/icons/icon-arrow-left.svg',
	iconEmail: '../../../../assets/icons/icon-email.svg',
	iconLinkedin: '../../../../assets/icons/icon-linkedin.svg',
	iconYoutube: '../../../../assets/icons/icon-youtube.svg',
	iconFacebook: '../../../../assets/icons/icon-facebook.svg',
	iconInstagram: '../../../../assets/icons/icon-instagram.svg',
	iconTwitter: '../../../../assets/icons/icon-twitter.svg',
	iconViewGrid: '../../../../assets/icons/icon-view-grid.svg',
	iconFilter: '../../../../assets/icons/icon-filter.svg',
};
